title: From Mississippi With Love
author: Vera
email: chem2ts@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 Let's see what's cooking in MS.

# social links
twitter_username: FromMsWluv
github_username:  V-for-Veronika

show_excerpts: true # set to false to remove excerpts on the homepage
